-- 코드를 입력하세요
SELECT 
    a.AUTHOR_ID, 
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * s.SALES) AS TOTAL_SALES
FROM AUTHOR a
JOIN BOOK b
    ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
) s
    ON b.BOOK_ID = s.BOOK_ID
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;