-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT c.ID, g.DEPTH + 1
    FROM ECOLI_DATA c JOIN GEN g
        ON c.PARENT_ID = g.ID
)

SELECT ID
FROM GEN
WHERE DEPTH = 3
ORDER BY ID;