-- 코드를 작성해주세요
WITH RECURSIVE tmp AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT s.ID, tmp.GENERATION + 1
    FROM tmp JOIN ECOLI_DATA s
    WHERE tmp.ID = s.PARENT_ID
)

SELECT ID
FROM tmp
WHERE GENERATION = 3
ORDER BY ID