-- 코드를 입력하세요
SELECT r1.FOOD_TYPE, r1.REST_ID, r1.REST_NAME, r1.FAVORITES
FROM REST_INFO r1 JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) r2
    ON r1.FOOD_TYPE = r2.FOOD_TYPE AND r1.FAVORITES = r2.MAX_FAV
ORDER BY FOOD_TYPE DESC;

