-- 코드를 입력하세요
SELECT 
    u.USER_ID,
    u.NICKNAME,
    CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) AS `전체주소`,
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS `전화번호`
FROM USED_GOODS_USER u 
JOIN USED_GOODS_BOARD b
    ON u.USER_ID = b.WRITER_ID
GROUP BY u.USER_ID
HAVING COUNT(DISTINCT BOARD_ID) >= 3
ORDER BY USER_ID DESC;