-- 코드를 작성해주세요
WITH RECURSIVE tmp AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT s.ID, s.PARENT_ID, tmp.GENERATION + 1
    FROM tmp JOIN ECOLI_DATA s
    ON tmp.ID = s.PARENT_ID
)

SELECT COUNT(*) COUNT, GENERATION
FROM tmp
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM tmp
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION