-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS DEPTH
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT c.ID, c.PARENT_ID, g.DEPTH + 1
    FROM ECOLI_DATA c JOIN GEN g
        ON c.PARENT_ID = g.ID
)

SELECT COUNT(*) COUNT, DEPTH GENERATION
FROM GEN
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM GEN
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;