-- 코드를 입력하세요
SELECT 
    h.HISTORY_ID, 
    FLOOR((DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE * (100 - IFNULL(p.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c
    ON h.CAR_ID = c.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE
    AND (
        (p.DURATION_TYPE = '7일 이상' AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 30)
        OR (p.DURATION_TYPE = '30일 이상' AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 90)
        OR (p.DURATION_TYPE = '90일 이상' AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90)
    )
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;

