-- 코드를 입력하세요
WITH RECURSIVE T AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM T
    WHERE HOUR < 23
)

SELECT t.HOUR AS HOUR, COUNT(a.ANIMAL_ID) AS COUNT
FROM T t LEFT JOIN ANIMAL_OUTS a
    ON t.HOUR = HOUR(a.DATETIME)
GROUP BY t.HOUR
ORDER BY HOUR;