-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 AS HOUR
    FROM TIME
    WHERE HOUR < 23
)

SELECT 
    t.HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM TIME t
LEFT JOIN ANIMAL_OUTS a
    ON t.HOUR = HOUR(a.DATETIME)
GROUP BY t.HOUR
ORDER BY HOUR;
    