-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, b.TOTAL_SALES
FROM USED_GOODS_USER u JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) b
    ON u.USER_ID = b.WRITER_ID
ORDER BY TOTAL_SALES;