-- 코드를 작성해주세요
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i 
JOIN ITEM_TREE t
    ON i.ITEM_ID = t.ITEM_ID
JOIN ITEM_INFO p
    ON t.PARENT_ITEM_ID = p.ITEM_ID
WHERE p.RARITY = 'RARE'
ORDER BY i.ITEM_ID DESC;