-- 코드를 입력하세요
SELECT MONTH(h.START_DATE) AS MONTH, h.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) r
    ON h.CAR_ID = r.CAR_ID
WHERE h.START_DATE >= '2022-08-01' AND h.START_DATE < '2022-11-01'
GROUP BY MONTH(h.START_DATE), h.CAR_ID
ORDER BY MONTH, CAR_ID DESC;
