-- 코드를 입력하세요
SELECT F.FLAVOR 
FROM FIRST_HALF F
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL
            FROM JULY
            GROUP BY FLAVOR) J
ON F.FLAVOR = J.FLAVOR
ORDER BY TOTAL_ORDER + J.J_TOTAL DESC
LIMIT 3