-- 코드를 작성해주세요
SELECT i1.ID, n.FISH_NAME, i1.LENGTH
FROM FISH_INFO i1
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) i2
    ON i1.FISH_TYPE = i2.FISH_TYPE AND i1.LENGTH = i2.LENGTH
JOIN FISH_NAME_INFO n
    ON i1.FISH_TYPE = n.FISH_TYPE
ORDER BY ID;
