-- 코드를 작성해주세요
SELECT f1.ID, n.FISH_NAME, f1.LENGTH
FROM FISH_INFO f1 JOIN FISH_NAME_INFO n
    ON f1.FISH_TYPE = n.FISH_TYPE
WHERE f1.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO f2
    WHERE f1.FISH_TYPE = f2.FISH_TYPE
)
ORDER BY ID;
