-- 코드를 입력하세요
SELECT c.CATEGORY, SUM(s.SALES) AS TOTAL_SALES
FROM BOOK c JOIN BOOK_SALES s
    ON c.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE >= '2022-01-01' AND s.SALES_DATE < '2022-02-01'
GROUP BY c.CATEGORY
ORDER BY CATEGORY;