-- 코드를 입력하세요
SELECT 
    f1.CATEGORY, 
    f2.MAX_PRICE,
    f1.PRODUCT_NAME
FROM FOOD_PRODUCT f1
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) f2
    ON f1.CATEGORY = f2.CATEGORY AND f1.PRICE = f2.MAX_PRICE
ORDER BY MAX_PRICE DESC;