-- 코드를 작성해주세요
WITH SKILLS AS (
    SELECT
        MAX(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END) AS PYTHON_CODE,
        MAX(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END) AS CSHARP_CODE,
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT_CODE
    FROM SKILLCODES
)

SELECT 
    CASE
        WHEN SKILL_CODE & PYTHON_CODE > 0 AND SKILL_CODE & FRONT_CODE > 0 THEN 'A'
        WHEN SKILL_CODE & CSHARP_CODE > 0 THEN 'B'
        WHEN SKILL_CODE & FRONT_CODE > 0 THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS
CROSS JOIN SKILLS
WHERE SKILL_CODE & CSHARP_CODE > 0 OR SKILL_CODE & FRONT_CODE > 0
ORDER BY GRADE, ID