-- 코드를 작성해주세요
WITH SKILLS AS (
    SELECT
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT_CODE,
        MAX(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END) AS CSHARP_CODE,
        MAX(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END) AS PYTHON_CODE
    FROM SKILLCODES
)

SELECT
    CASE
        WHEN d.SKILL_CODE & s.FRONT_CODE > 0 AND d.SKILL_CODE & s.PYTHON_CODE > 0 THEN 'A'
        WHEN d.SKILL_CODE & s.CSHARP_CODE > 0 THEN 'B'
        WHEN d.SKILL_CODE & s.FRONT_CODE > 0 THEN 'C'
    END AS GRADE,
    d.ID,
    d.EMAIL
FROM DEVELOPERS d
    CROSS JOIN SKILLS s
WHERE d.SKILL_CODE & s.FRONT_CODE > 0 OR d.SKILL_CODE & s.CSHARP_CODE > 0
ORDER BY GRADE, ID;
